version: '2'

services:
  caddy:
    image: "expoll-web:latest"
    build:
      context: ./
      dockerfile: ./caddy/Dockerfile
    restart: unless-stopped
    container_name: expoll_caddy
    hostname: expoll_caddy
    networks:
      - expoll_net
      - out
    #ports:
    #    - "80:80"

networks:
  expoll_net:
    name: expoll_net
    external: true
  out:
    name: out
    external: true